const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const babel=require('@babel/core');
const html=fs.readFileSync('index.html','utf8');
const script=html.match(/<script type="text\/babel">([\s\S]*?)<\/script>/)[1];
const code=babel.transformSync(script,{plugins:['@babel/plugin-transform-react-jsx'],configFile:false,babelrc:false}).code;
function app(overrides={}) {
  const state=[];let index=0;
  const React={createElement:(type,props,...children)=>({type,props:props||{},children}),createContext:v=>({value:v}),useContext:()=>({lang:'es',t:k=>k}),useEffect:()=>{},useRef:v=>({current:v}),useMemo:fn=>fn(),useCallback:fn=>fn,useState:initial=>{const i=index++;if(!(i in state))state[i]=typeof initial==='function'?initial():initial;return [state[i],v=>state[i]=typeof v==='function'?v(state[i]):v];}};
  const context=vm.createContext({React,ReactDOM:{createRoot:()=>({render:()=>{}})},document:{getElementById:()=>({})},localStorage:{getItem:()=>null},Date,console,setTimeout,clearTimeout,AbortSignal,...overrides});
  vm.runInContext(code+'\nglobalThis.api={validNumber,todayISO,mkSample,loadStored,monthMatrix,expandDateRange,parseNumberQuery,NewSampleModal,DocModal,ClientModal,Reports,simulateReport,DEFAULT_CLIENTS,DEFAULT_SPECIALTIES,INITIAL_SAMPLES,aiComplete};',context);
  return {...context.api,state,render:(fn,props)=>{index=0;return fn(props);}};
}
function nodes(tree,predicate) {const out=[];function walk(x){if(!x||typeof x!=='object')return;if(Array.isArray(x)){x.forEach(walk);return;}if(predicate(x))out.push(x);x.children?.forEach(walk);}walk(tree);return out;}
test('entire JSX compiles and application module initializes',()=>assert.ok(app().INITIAL_SAMPLES.length));
test('numeric validation rejects empty, negative, non-finite and fractional ages',()=>{const a=app();for(const value of ['', ' ', -1, 121, 1.2,Infinity,'abc'])assert.equal(a.validNumber(value,0,120,true),false);for(const value of [0,'0',40,120])assert.equal(a.validNumber(value,0,120,true),true);});
test('new sample submission rejects negative age and accepts a newborn',()=>{const a=app();const added=[];const props={clients:a.DEFAULT_CLIENTS,specialties:a.DEFAULT_SPECIALTIES,insurers:[],doctors:[],onAdd:s=>added.push(s),addInsurer:()=>{},addDoctor:()=>{}};a.render(a.NewSampleModal,props);Object.assign(a.state[0],{type:'QA ficticia',patient:'QA',age:'-1'});let tree=a.render(a.NewSampleModal,props);let button=nodes(tree,n=>n.type==='button'&&n.props.className==='btn btn-primary').at(-1);assert.ok(button.props.disabled);button.props.onClick();assert.equal(added.length,0);a.state[0].age='0';tree=a.render(a.NewSampleModal,props);button=nodes(tree,n=>n.type==='button'&&n.props.className==='btn btn-primary').at(-1);assert.equal(!!button.props.disabled,false);button.props.onClick();assert.equal(added.length,1);assert.ok(added[0].caseCode.startsWith(String(new Date().getFullYear()).slice(-2)));assert.ok(added[0].receivedAt);});
test('client change removes previously selected billing lines',()=>{const a=app();const props={type:'factura',clients:a.DEFAULT_CLIENTS,samples:a.INITIAL_SAMPLES};a.render(a.DocModal,props);a.state[3]=[{concept:'QA',qty:1,unitPrice:10,sampleId:a.INITIAL_SAMPLES[0].id}];let tree=a.render(a.DocModal,props);nodes(tree,n=>n.type==='select')[0].props.onChange({target:{value:a.DEFAULT_CLIENTS[1].id}});assert.equal(a.state[3].length,0);});
test('billing rejects negative amounts, zero quantities and foreign samples',()=>{const a=app();const props={type:'factura',clients:a.DEFAULT_CLIENTS,samples:a.INITIAL_SAMPLES};a.render(a.DocModal,props);for(const line of [{concept:'QA',qty:1,unitPrice:-1},{concept:'QA',qty:0,unitPrice:1},{concept:'QA',qty:1,unitPrice:1,sampleId:a.INITIAL_SAMPLES[0].id}]){a.state[3]=[line];const tree=a.render(a.DocModal,props);assert.ok(nodes(tree,n=>n.type==='button'&&n.props.className==='btn btn-primary').at(-1).props.disabled);}});
test('storage with wrong collection type falls back',()=>{for(const [raw,fallback] of [['{}',[]],['[]',{}],['[null]',[]],['broken',[]]]){const a=app({localStorage:{getItem:()=>raw}});assert.equal(a.loadStored('test',fallback),fallback);}});
test('calendar includes leap day and crosses years',()=>{const a=app();assert.equal(a.monthMatrix(2024,1).filter(Boolean).length,29);assert.deepEqual(Array.from(a.expandDateRange('2025-12-31','2026-01-02')),['2025-12-31','2026-01-01','2026-01-02']);});
test('empty AI response is an error',async()=>{const a=app({fetch:async()=>({ok:true,json:async()=>({choices:[]})})});await assert.rejects(a.aiComplete('',{messages:[{role:'user',content:'QA'}]}),/vacía/);});
test('AI fetch has bounded timeout and returns valid text',async()=>{let request;const a=app({fetch:async(url,options)=>{request=options;return {ok:true,json:async()=>({choices:[{message:{content:'QA'}}]})};}});assert.equal(await a.aiComplete('',{messages:[{role:'user',content:'QA'}]}),'QA');assert.ok(request.signal);});
test('simulated report preserves findings without inventing a diagnosis or code',()=>{const a=app();const text=a.simulateReport(a.INITIAL_SAMPLES[0],'Dermatopatología','','macro QA','micro QA');assert.ok(text.includes('macro QA'));assert.ok(text.includes('micro QA'));assert.ok(text.includes('[PENDIENTE: codificación'));assert.ok(!text.includes('M-87203'));assert.ok(!text.includes('compatibles con'));});
test('local date does not use UTC day around midnight',()=>{class LocalDate extends Date {getFullYear(){return 2026;}getMonth(){return 8;}getDate(){return 15;}toISOString(){return '2026-09-14T22:30:00.000Z';}}assert.equal(app({Date:LocalDate}).todayISO(),'2026-09-15');});
